"""Add user activity table

Revision ID: d1b7fa84c72f
Revises: 4daef5a6df8e
Create Date: 2025-08-02 11:36:45.415339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b7fa84c72f'
down_revision: Union[str, Sequence[str], None] = '4daef5a6df8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_path')
    # ### end Alembic commands ###
